export const GET_CONTACT = 'GET_CONTACT'; // tipo de "accion" get para contact
export const DELETE_CONTACT = 'DELETE_CONTACT';// tipo de accion "delete" para contact 
export const ADD_CONTACT = 'ADD_CONTACT'; // tipo de accion "agreagar" para contact
export const GET_ERRORS = 'GET_ERRORS'; // tipo de accion "GET" para los errors
export const CREATE_MESSAGES = 'CREATE_MESSAGES'; // tipo de accion "create" para los menssages
export const USER_LOADING = 'USER_LOADING';// tipo de accion para identificar si un usuario se esta logueado
export const AUTH_ERROR = 'AUTH_ERROR';// tipo de accion para identificar que ocurrio un error al identificare
export const USER_LOADED = 'USER_LOADED';// tipo de accion  para identificar que el usuario esta logueado
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';// tipo de accion  para identificar que el login fue exitoso
export const LOGIN_FAIL = 'LOGIN_FAIL';// tipo de accion  para identificar que el login fallo
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';// tipo de accion para el logaut de la aplicacion
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';// tipo de accion para saber que el registro fue exitoso
export const REGISTER_FAIL = 'REGISTER_FAIL';// tipo de accion para saber que el registro fue un fallo