# Generated by Django 3.1.1 on 2020-09-08 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('firtsName', models.CharField(max_length=80)),
                ('lastName', models.CharField(max_length=80)),
                ('nickName', models.CharField(max_length=50)),
                ('webSite', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=5000)),
                ('introduction', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='Blog')),
                ('status', models.BooleanField(default=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.category')),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.comment')),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.author')),
                ('disLikePost_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='noLikePost', to='Blog.reaction')),
                ('likePost_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='LikePost', to='Blog.reaction')),
                ('publisher_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='disLikeComment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='noLikeComment', to='Blog.reaction'),
        ),
        migrations.AddField(
            model_name='comment',
            name='likeComment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='LikeComment', to='Blog.reaction'),
        ),
    ]
