# Generated by Django 3.1.1 on 2020-09-08 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=600)),
                ('subject', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 9, 8, 11, 45, 49, 792034))),
            ],
        ),
    ]
